---
title: "Getting Started in R"
date: 2020-06-04
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```

# Why R?

Perhaps the best place to start is to ask ourselves why we are choosing to use R. Fortunately, Rob Schlegel (WHOI) sums up nicely why using R is a good idea for data science as part of his R workshop:

https://robwschlegel.github.io/Intro_R_Workshop/prelim.html#why-use-r

Dan Kelley (Dalhousie) has a nice book on oceanographic analysis in R (in classroom) - his sub-chapter on "Why R, and Why Now?" is a quick read and is on GC as a pdf.

Please read both these short justifications to give you an insight into why R is something worth your energy.

# Downloading R and Rstudio

You should next download both R (the programming language) and Rstudio (a nice visual interface that makes writing code more intuitive) and opened RStudio to see that it has worked properly.

You need to download R first:

* Go to http://www.r-project.org/ and choose "download R" under "Getting Started".
* Select any of the sites to download R from
* Choose the R link for your operating system
* **Windows**: select "base" and then "Download R for Windows". Run the .exe file that you download to install R
* **Mac**: select the .pkg link to download. Run the file that you download to install.

Then you need to download RStudio:

* Go to http://www.rstudio.com
* Click "Download RStudio" and following the instructions for your operating system.

To use R you need to open RStudio (not the R link that might have appeared on your desktop).

# Intro to R

If you've never used R or RStudio before it's worth a little bit of orientation.

You can some basics from this tutorial:

https://www.udemy.com/course/machlearn1/

You will need to sign in. Go through the "Getting Started" section (< 20mins) to get the real basics.


